apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appname}}
type: Opaque
data:
  password: {{ .Values.database.password | default "defaultpassword" | b64enc }}
