apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appname}}
spec:
  clusterIP: None  # Headless service
  selector:
    app: {{ .Values.appname}}
  ports:
    - port: 5000
      targetPort: 5000
